### ISSUE TITLE
How to use a function_group as a higher order function?

### ISSUE THREAD

**Issue by jjpe** [Jon-Davis/function_group#1]
Consider an extended version of your example:
``` rust
    struct TestStruct(usize);

    function_group! {
        fn add_to_struct(&mut self: TestStruct) {
            (one : usize) {
                self.0 += one;
            }
            (one : usize, two : usize){
                self.0 += one + two;
            }
        }
    }

    fn foo() {
        let x: Box<dyn add_to_struct<_>> = &self::add_to_struct; // Fails to compile 
    }
```

The indicated line causes a compile error:
```
error[E0423]: expected value, found trait `self::add_to_struct`
   --> src/eval/function.rs:197:53
    |
197 |         let x: Box<dyn add_to_struct<_>> = Box::new(self::add_to_struct);
    |                                                     ^^^^^^^^^^^^^^^^^^^ not a value
```

How can I store a function_group in e.g. a struct, or a local var (as the example tries to do)?

**Comment by Jon-Davis** [comment]
Sorry about the delay, I haven't touched the code in a bit, and it is kind of complex.

A function group isn't really a thing, and as such storing it might not be a good approach as you can only store 1 function pointer into a variable, which means you wont really be able to call the different variants of the function.

The macro generates different code depending on whether you are just creating a function or if you are adding a function to a struct. if you are wanting to store a method of a struct generated using function group than you could just save the method.

```rust
fn test_function_group_method_generic() {
    // store the function like so
    let function = TestStruct::add_to_struct;
    let mut x = TestStruct(10);
    // use the following syntax to call the function, simply pass in the struct as the first argument
    function(&mut x, (1,2));
    // function(&mut x, (0,)); // This would fail because the stored function is only for a tuple with 2 elements
    assert!(x.0 == 13);
}
```

If you need the type information as well to store it in a struct, there is some extra steps. Under the hood what happens in function group creates a trait called `add_to_struct` which contains the function definition, then it implements that trait on the struct for each argument. Storing this function is tedious and would look something like this.
```rust

fn test_function_group_method_generic_struct() {
    // example struct that stores a function x which is an implementation of the add_to_struct trait
    struct WrapperStruct<'a, Input> where TestStruct : add_to_struct<Input> {
        x : &'a dyn Fn(&mut TestStruct, Input) -> (),
    }

    let wrapper_struct = WrapperStruct{x: &TestStruct::add_to_struct};
    let mut x = TestStruct(10);

    //calling the wrapper struct
    (wrapper_struct.x)(&mut x, (1,2));
    // (wrapper_struct.x)(&mut x, (0,)); // again this will fail as the stored function is for a tuple with 2 elements
    assert!(x.0 == 13);
}
```
I wouldn't really recommend this approach because you would only be saving the function pointer to the function for a particular input.

**Comment by jjpe** [comment]
Indeed those characteristics make `function_group` less suited to my requirements.
However, you have still given me a good idea regarding how to go about this myself.
So, thanks!
